void citirematr(int a[][100],int &n);
void afisarematr(int a[][100],int n);
void elemmaxlin(int a[][100],int n);
int sumzona(int a[][100],int n,int z,int &ok);
int verifsimetrie(int a[][100],int n);
long long proddiagsec(int a[][100],int n);
void rotirest(int a[][100],int b[][100],int n);
void rotiredr(int a[][100],int b[][100],int n);
void bordare(int a[][100],int &n,int x);
void copiere(int a[][100],int b[][100],int n);
